"""notebook update


Revision ID: a46046cece40
Revises: 7247dff2b5ab
Create Date: 2019-11-25 23:22:18.671989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46046cece40'
down_revision = '7247dff2b5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jupyter_notebook', sa.Column('script_type', sa.Enum('QA', 'TASK', 'REPORT', name='scripttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jupyter_notebook', 'script_type')
    # ### end Alembic commands ###
